### ISSUE TITLE
Model training with large embeddings

### ISSUE THREAD

**Issue by andodet** [AFAgarap/ecommerce-reviews-analysis#3]
Hi Abien,

First of all thanks for all the good work!

I am taking inspiration from your notebook to test similar models on reviews left on an Italian ecommerce website. Both the embedding matrix and word vectorization lead to high memory usage.
Was wondering what did you train this model on.

Might consider to spin up a vm on GCP  and take it that way.

Cheers.

**Comment by AFAgarap** [comment]
Hello Andrea!

I apologize for the late response.
Thank you for taking interest in my work. I worked on this project in a laptop computer with 16GB RAM, so if you have a computer with similar specification, I suppose there'd be no need for using a GCP VM.
The embedding I used in this project was GloVe with 840B tokens in 300 dimensions. I had to  use a smaller architecture (Bidirectional RNN with 256 LSTM cells), and a smaller batch size of 256.
